"""feat: separate patient info from clinical data

Revision ID: 00ab9082c9f6
Revises: e8a3f2d9c104
Create Date: 2026-04-30 14:09:21.470412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ab9082c9f6'
down_revision: Union[str, Sequence[str], None] = 'e8a3f2d9c104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uix_patients_facility_mrn_active'), postgresql_where='((is_deleted = false) AND (medical_record_number IS NOT NULL))')
        batch_op.drop_index(batch_op.f('uix_patients_facility_phone_active'), postgresql_where='(is_deleted = false)')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uix_patients_facility_phone_active'), ['facility_id', 'phone'], unique=True, postgresql_where='(is_deleted = false)')
        batch_op.create_index(batch_op.f('uix_patients_facility_mrn_active'), ['facility_id', 'medical_record_number'], unique=True, postgresql_where='((is_deleted = false) AND (medical_record_number IS NOT NULL))')

    # ### end Alembic commands ###
