"""feat: add pregnancy closes at

Revision ID: 3de23752f53f
Revises: f4b8c2d9a731
Create Date: 2026-04-30 18:06:34.545565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de23752f53f'
down_revision: Union[str, Sequence[str], None] = 'f4b8c2d9a731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
