"""add  tables

Revision ID: 51464e6dcadd
Revises: 
Create Date: 2026-03-10 03:08:37.547313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51464e6dcadd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('facility_manager_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_manager_id'], ['users.id'], name='fk_facility_manager_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index('idx_facility_manager_created', ['facility_manager_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_facilities_facility_manager_id'), ['facility_manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_facility_name'), ['facility_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_facilities_id'), ['id'], unique=False)

    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('SCAN_DUE_REMINDERS', 'SEND_REMINDER_SMS', 'SEND_REMINDER_EMAIL', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.create_index('idx_jobqueue_status_scheduled', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index('idx_jobqueue_type_status', ['job_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_queue_status'), ['status'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='fk_user_facility_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('geographic_restrictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('allowed_countries', sa.Text(), nullable=False, comment='JSON array of ISO country codes e.g. ["GH", "NG", "KE"]'),
    sa.Column('blocked_countries', sa.Text(), nullable=True, comment='JSON array of ISO country codes to block'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geographic_restrictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geographic_restrictions_facility_id'), ['facility_id'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique notification log ID'),
    sa.Column('recipient_id', sa.UUID(), nullable=False, comment='ID of the recipient (patient/staff)'),
    sa.Column('recipient_type', sa.String(length=50), nullable=False, comment='Type of recipient (patient, staff, etc.)'),
    sa.Column('recipient_name', sa.String(length=255), nullable=False, comment='Name of recipient at time of sending'),
    sa.Column('recipient_email', sa.String(length=255), nullable=True, comment='Email address used'),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True, comment='Phone number used'),
    sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', 'PUSH', 'IN_APP', name='notificationchannel'), nullable=False, comment='Channel used (email, sms, etc.)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Email subject or SMS title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Message content sent'),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='Type of notification (reminder, alert, etc.)'),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'BOUNCED', 'DELIVERED', name='notificationstatus'), nullable=False, comment='Current delivery status'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When notification was sent'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='When notification was delivered (if tracked)'),
    sa.Column('failed_at', sa.DateTime(), nullable=True, comment='When notification failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='Service provider used (twilio, termii, etc.)'),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True, comment="Provider's message ID for tracking"),
    sa.Column('triggered_by', sa.String(length=50), nullable=False, comment='What triggered this notification (scheduler, manual, etc.)'),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True, comment='User who triggered (if manual)'),
    sa.Column('batch_id', sa.UUID(), nullable=True, comment='Batch ID for grouped notifications'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When log entry was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index('idx_notification_batch', ['batch_id', 'status'], unique=False)
        batch_op.create_index('idx_notification_recipient_date', ['recipient_id', 'sent_at'], unique=False)
        batch_op.create_index('idx_notification_status_channel', ['status', 'channel', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_type_date', ['notification_type', 'sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('patient_type', postgresql.ENUM('REGULAR', 'PREGNANT', name='patienttype'), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'POSTPARTUM', 'COMPLETED', 'INACTIVE', name='patientstatus'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('accepts_messaging', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_accepts_messaging'), ['accepts_messaging'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_type'), ['patient_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_updated_by_id'), ['updated_by_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('absolute_expiry', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False, comment='Fixed ID=1 for singleton pattern'),
    sa.Column('notification_target', sa.String(length=50), nullable=False, comment='Target audience for notifications'),
    sa.Column('reminder_interval_days', sa.Integer(), nullable=False, comment='Days between vaccination reminders (1-30)'),
    sa.Column('reminder_message', sa.Text(), nullable=True, comment='Custom reminder message template'),
    sa.Column('dashboard_refresh_rate_seconds', sa.Integer(), nullable=False, comment='Auto-refresh interval in seconds (10-300)'),
    sa.Column('enable_dashboard_auto_refresh', sa.Boolean(), nullable=False, comment='Enable/disable dashboard auto-refresh'),
    sa.Column('system_status', sa.String(length=20), nullable=False, comment='Current system operational status'),
    sa.Column('maintenance_message', sa.Text(), nullable=True, comment='Message displayed during maintenance'),
    sa.Column('maintenance_start', sa.DateTime(), nullable=True, comment='Scheduled maintenance start time'),
    sa.Column('maintenance_end', sa.DateTime(), nullable=True, comment='Scheduled maintenance end time'),
    sa.Column('require_device_approval', sa.Boolean(), nullable=False, comment='Require admin approval for new devices'),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, comment='User session timeout in minutes (30-1440)'),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False, comment='Maximum failed login attempts before lockout (3-10)'),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False, comment='Account lockout duration in minutes (10-120)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Settings creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='User who last updated settings'),
    sa.CheckConstraint('dashboard_refresh_rate_seconds >= 10 AND dashboard_refresh_rate_seconds <= 300', name='valid_refresh_rate'),
    sa.CheckConstraint('id = 1', name='single_settings_row'),
    sa.CheckConstraint('lockout_duration_minutes >= 10 AND lockout_duration_minutes <= 120', name='valid_lockout_duration'),
    sa.CheckConstraint('max_login_attempts >= 3 AND max_login_attempts <= 10', name='valid_max_login_attempts'),
    sa.CheckConstraint('reminder_interval_days >= 1 AND reminder_interval_days <= 30', name='valid_reminder_interval'),
    sa.CheckConstraint('session_timeout_minutes >= 30 AND session_timeout_minutes <= 1440', name='valid_session_timeout'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('idx_settings_status', ['system_status'], unique=False)
        batch_op.create_index('idx_settings_updated', ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_notification_target'), ['notification_target'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_system_status'), ['system_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_updated_at'), ['updated_at'], unique=False)

    op.create_table('trusted_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('last_ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRUSTED', 'BLOCKED', 'SUSPICIOUS', name='devicestatus'), nullable=False),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusted_devices_device_fingerprint'), ['device_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_trusted_devices_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_trusted_devices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusted_devices_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('session_token', sa.String(length=512), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('login_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('terminated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vaccines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('price_per_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_quantity_non_negative'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_reserved_lte_quantity'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_reserved_non_negative'),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccines_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccines_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccines_vaccine_name'), ['vaccine_name'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('diagnosed_by_id', sa.UUID(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('preliminary_diagnosis', sa.Text(), nullable=True),
    sa.Column('actual_diagnosis', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('diagnosed_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnosed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnoses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnoses_patient_id'), ['patient_id'], unique=False)

    op.create_table('patient_vaccine_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('price_per_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=False),
    sa.Column('total_package_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('doses_administered', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paid <= total_package_price', name='ck_amount_paid_lte_total'),
    sa.CheckConstraint('price_per_dose >= 0', name='ck_price_per_dose_non_negative'),
    sa.CheckConstraint('total_doses > 0', name='ck_total_doses_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_vaccine_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_vaccine_purchases_vaccine_id'), ['vaccine_id'], unique=False)
        batch_op.create_index('uix_one_active_purchase_per_patient_vaccine', ['patient_id', 'vaccine_id'], unique=True, postgresql_where='is_active = TRUE')

    op.create_table('pregnant_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gravida', sa.Integer(), server_default='1', nullable=False),
    sa.Column('para', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_prescription_date'), ['prescription_date'], unique=False)

    op.create_table('regular_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('viral_load', sa.String(length=100), nullable=True),
    sa.Column('last_viral_load_date', sa.Date(), nullable=True),
    sa.Column('treatment_start_date', sa.Date(), nullable=True),
    sa.Column('treatment_regimen', sa.String(length=255), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('months_supply', sa.Integer(), nullable=True),
    sa.Column('next_dose_due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('lab_review_scheduled', sa.Boolean(), nullable=False),
    sa.Column('lab_review_date', sa.Date(), nullable=True),
    sa.Column('lab_review_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_schedules_next_dose_due_date'), ['next_dose_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_schedules_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_schedules_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_schedules_scheduled_date'), ['scheduled_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_purchase_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vaccine_purchase_id'], ['patient_vaccine_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_vaccine_purchase_id'), ['vaccine_purchase_id'], unique=False)

    op.create_table('pregnancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_number', sa.Integer(), nullable=False),
    sa.Column('lmp_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('gestational_age_weeks', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', postgresql.ENUM('LIVE_BIRTH', 'STILLBIRTH', 'MISCARRIAGE', 'ABORTION', 'ECTOPIC', name='pregnancy_outcome'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pregnancy_number > 0', name='ck_pregnancy_number_positive'),
    sa.ForeignKeyConstraint(['patient_id'], ['pregnant_patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'pregnancy_number', name='uq_patient_pregnancy_number')
    )
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pregnancies_expected_delivery_date'), ['expected_delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pregnancies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pregnancies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_pregnancies_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('uix_one_active_pregnancy_per_patient', ['patient_id'], unique=True, postgresql_where='is_active = TRUE')

    op.create_table('vaccinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_purchase_id', sa.UUID(), nullable=False),
    sa.Column('dose_number', postgresql.ENUM('FIRST_DOSE', 'SECOND_DOSE', 'THIRD_DOSE', name='dosetype'), nullable=False),
    sa.Column('dose_date', sa.Date(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('vaccine_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('administered_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_purchase_id'], ['patient_vaccine_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccinations_dose_date'), ['dose_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccinations_dose_number'), ['dose_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccinations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccinations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccinations_vaccine_purchase_id'), ['vaccine_purchase_id'], unique=False)

    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', name='sex'), nullable=True),
    sa.Column('six_month_checkup_date', sa.Date(), nullable=True),
    sa.Column('six_month_checkup_completed', sa.Boolean(), nullable=False),
    sa.Column('hep_b_antibody_test_result', postgresql.ENUM('POSITIVE', 'NEGATIVE', 'INDETERMINATE', 'PENDING', name='hep_b_test_result'), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_date_of_birth'), ['date_of_birth'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_pregnancy_id'), ['pregnancy_id'], unique=False)

    op.create_table('patient_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', postgresql.ENUM('DELIVERY_WEEK', 'CHILD_6MONTH_CHECKUP', 'MEDICATION_DUE', 'PAYMENT_DUE', 'VACCINATION_DUE', name='remindertype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_reminders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_reminders_reminder_type'), ['reminder_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_reminders_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_reminders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_patient_reminders_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_patient_reminders_reminder_type'))
        batch_op.drop_index(batch_op.f('ix_patient_reminders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_reminders_id'))

    op.drop_table('patient_reminders')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_pregnancy_id'))
        batch_op.drop_index(batch_op.f('ix_children_id'))
        batch_op.drop_index(batch_op.f('ix_children_date_of_birth'))

    op.drop_table('children')
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccinations_vaccine_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_vaccinations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_vaccinations_id'))
        batch_op.drop_index(batch_op.f('ix_vaccinations_dose_number'))
        batch_op.drop_index(batch_op.f('ix_vaccinations_dose_date'))

    op.drop_table('vaccinations')
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.drop_index('uix_one_active_pregnancy_per_patient', postgresql_where='is_active = TRUE')
        batch_op.drop_index(batch_op.f('ix_pregnancies_patient_id'))
        batch_op.drop_index(batch_op.f('ix_pregnancies_is_active'))
        batch_op.drop_index(batch_op.f('ix_pregnancies_id'))
        batch_op.drop_index(batch_op.f('ix_pregnancies_expected_delivery_date'))

    op.drop_table('pregnancies')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_vaccine_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_schedules_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_medication_schedules_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_medication_schedules_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medication_schedules_next_dose_due_date'))
        batch_op.drop_index(batch_op.f('ix_medication_schedules_id'))

    op.drop_table('medication_schedules')
    op.drop_table('regular_patients')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescription_date'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))

    op.drop_table('prescriptions')
    op.drop_table('pregnant_patients')
    with op.batch_alter_table('patient_vaccine_purchases', schema=None) as batch_op:
        batch_op.drop_index('uix_one_active_purchase_per_patient_vaccine', postgresql_where='is_active = TRUE')
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_vaccine_id'))
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_payment_status'))
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_is_active'))
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_id'))
        batch_op.drop_index(batch_op.f('ix_patient_vaccine_purchases_batch_number'))

    op.drop_table('patient_vaccine_purchases')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnoses_patient_id'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_diagnoses_id'))

    op.drop_table('diagnoses')
    with op.batch_alter_table('vaccines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccines_vaccine_name'))
        batch_op.drop_index(batch_op.f('ix_vaccines_is_published'))
        batch_op.drop_index(batch_op.f('ix_vaccines_id'))
        batch_op.drop_index(batch_op.f('ix_vaccines_batch_number'))

    op.drop_table('vaccines')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_trusted_devices_status'))
        batch_op.drop_index(batch_op.f('ix_trusted_devices_id'))
        batch_op.drop_index(batch_op.f('ix_trusted_devices_device_fingerprint'))

    op.drop_table('trusted_devices')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_updated_at'))
        batch_op.drop_index(batch_op.f('ix_settings_system_status'))
        batch_op.drop_index(batch_op.f('ix_settings_notification_target'))
        batch_op.drop_index('idx_settings_updated')
        batch_op.drop_index('idx_settings_status')

    op.drop_table('settings')
    op.drop_table('role_permissions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_type'))
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_facility_id'))
        batch_op.drop_index(batch_op.f('ix_patients_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_patients_accepts_messaging'))

    op.drop_table('patients')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_channel'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_batch_id'))
        batch_op.drop_index('idx_notification_type_date')
        batch_op.drop_index('idx_notification_status_channel')
        batch_op.drop_index('idx_notification_recipient_date')
        batch_op.drop_index('idx_notification_batch')

    op.drop_table('notification_logs')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_success'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('geographic_restrictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geographic_restrictions_facility_id'))

    op.drop_table('geographic_restrictions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    op.drop_table('permissions')
    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_queue_status'))
        batch_op.drop_index(batch_op.f('ix_job_queue_job_type'))
        batch_op.drop_index(batch_op.f('ix_job_queue_id'))
        batch_op.drop_index('idx_jobqueue_type_status')
        batch_op.drop_index('idx_jobqueue_status_scheduled')

    op.drop_table('job_queue')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_id'))
        batch_op.drop_index(batch_op.f('ix_facilities_facility_name'))
        batch_op.drop_index(batch_op.f('ix_facilities_facility_manager_id'))
        batch_op.drop_index(batch_op.f('ix_facilities_email'))
        batch_op.drop_index(batch_op.f('ix_facilities_created_at'))
        batch_op.drop_index('idx_facility_manager_created')

    op.drop_table('facilities')
    # ### end Alembic commands ###
