"""add notes, reserve and quantity to vaccine and vaccine purchase models

Revision ID: 8298527c4a35
Revises: e0042e45a842
Create Date: 2026-03-05 17:38:15.494116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8298527c4a35'
down_revision: Union[str, Sequence[str], None] = 'e0042e45a842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up any leftover temp table from a previously failed migration run
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_children")
    with op.batch_alter_table('children', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('updated_by_id', sa.String(32), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('pregnancy_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('hep_b_antibody_test_result',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_children_updated_by_id_users', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('diagnosed_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('facility_manager_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('geographic_restrictions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('facility_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('medication_schedules', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.String(32), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('updated_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medication_schedules_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_foreign_key('fk_medication_schedules_prescription_id_prescriptions', 'prescriptions', ['prescription_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('recipient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('triggered_by_user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.alter_column('batch_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('patient_reminders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('child_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('patient_vaccine_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('vaccine_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('created_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.drop_column('balance')

    with op.batch_alter_table('patients', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('facility_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('created_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.alter_column('updated_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_patients_facility_id_facilities', 'facilities', ['facility_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('vaccine_purchase_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('received_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('pregnant_patients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('prescribed_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.alter_column('updated_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('regular_patients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('approved_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('facility_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('vaccine_purchase_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('administered_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)

    with op.batch_alter_table('vaccines', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('reserved_quantity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=False)
        batch_op.alter_column('added_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(32),
               existing_nullable=True)
        batch_op.create_check_constraint('ck_quantity_non_negative', 'quantity >= 0')
        batch_op.create_check_constraint('ck_reserved_non_negative', 'reserved_quantity >= 0')
        batch_op.create_check_constraint('ck_reserved_lte_quantity', 'reserved_quantity <= quantity')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccines', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint('ck_reserved_lte_quantity', type_='check')
        batch_op.drop_constraint('ck_reserved_non_negative', type_='check')
        batch_op.drop_constraint('ck_quantity_non_negative', type_='check')
        batch_op.alter_column('added_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('reserved_quantity')

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.alter_column('administered_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('vaccine_purchase_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('trusted_devices', schema=None) as batch_op:
        batch_op.alter_column('approved_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('regular_patients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('updated_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('prescribed_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pregnant_patients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('received_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('vaccine_purchase_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('updated_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('facility_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_patients_facility_id_facilities_cascade', 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('patient_vaccine_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.alter_column('created_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('vaccine_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('notes')

    with op.batch_alter_table('patient_reminders', schema=None) as batch_op:
        batch_op.alter_column('child_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('triggered_by_user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('recipient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('medication_schedules', schema=None, recreate='always') as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_schedules_prescription_id'))
        batch_op.alter_column('updated_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('prescription_id')

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('geographic_restrictions', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('facility_manager_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('diagnosed_by_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('children', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('hep_b_antibody_test_result',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('pregnancy_id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(32),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('updated_by_id')

    # ### end Alembic commands ###