"""add indexes

Revision ID: eb21b869f569
Revises: 51464e6dcadd
Create Date: 2026-03-16 22:59:51.218687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb21b869f569'
down_revision: Union[str, Sequence[str], None] = '51464e6dcadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index('idx_facility_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_facility_email', ['email'], unique=False)
        batch_op.create_foreign_key('fk_facility_manager_id', 'users', ['facility_manager_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.create_index('idx_jobqueue_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_jobqueue_locked_until', ['locked_until'], unique=False)
        batch_op.create_index('idx_jobqueue_scheduled_status_retries', ['scheduled_at', 'status', 'retry_count'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('idx_permissions_name_created_at', ['name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_permission_id', ['permission_id'], unique=False)
        batch_op.create_index('idx_role_permissions_role_id', ['role_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_roles_name_created_at', ['name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_assigned_at', ['assigned_at'], unique=False)
        batch_op.create_index('idx_user_roles_role_id', ['role_id'], unique=False)
        batch_op.create_index('idx_user_roles_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_facility_id', 'facilities', ['facility_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_facility_id', type_='foreignkey')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_user_id')
        batch_op.drop_index('idx_user_roles_role_id')
        batch_op.drop_index('idx_user_roles_assigned_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))
        batch_op.drop_index('idx_roles_name_created_at')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_role_id')
        batch_op.drop_index('idx_role_permissions_permission_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))
        batch_op.drop_index('idx_permissions_name_created_at')

    with op.batch_alter_table('job_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_jobqueue_scheduled_status_retries')
        batch_op.drop_index('idx_jobqueue_locked_until')
        batch_op.drop_index('idx_jobqueue_created_at')

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_facility_manager_id', type_='foreignkey')
        batch_op.drop_index('idx_facility_email')
        batch_op.drop_index('idx_facility_created_at')

    # ### end Alembic commands ###
