"""update tables

Revision ID: 499f88e28d1c
Revises: 
Create Date: 2025-12-08 11:28:33.041979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499f88e28d1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('facility_manager_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facility_manager_id'], ['users.id'], name='fk_facility_manager_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_manager_created', 'facilities', ['facility_manager_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_facilities_created_at'), 'facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_facilities_email'), 'facilities', ['email'], unique=True)
    op.create_index(op.f('ix_facilities_facility_manager_id'), 'facilities', ['facility_manager_id'], unique=False)
    op.create_index(op.f('ix_facilities_facility_name'), 'facilities', ['facility_name'], unique=True)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='fk_user_facility_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('geographic_restrictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('allowed_countries', sa.Text(), nullable=False),
    sa.Column('blocked_countries', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_restrictions_facility_id'), 'geographic_restrictions', ['facility_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_device_fingerprint'), 'login_attempts', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique notification log ID'),
    sa.Column('recipient_id', sa.UUID(), nullable=False, comment='ID of the recipient (patient/staff)'),
    sa.Column('recipient_type', sa.String(length=50), nullable=False, comment='Type of recipient (patient, staff, etc.)'),
    sa.Column('recipient_name', sa.String(length=255), nullable=False, comment='Name of recipient at time of sending'),
    sa.Column('recipient_email', sa.String(length=255), nullable=True, comment='Email address used'),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True, comment='Phone number used'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Channel used (email, sms, etc.)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Email subject or SMS title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Message content sent'),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='Type of notification (reminder, alert, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current delivery status'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When notification was sent'),
    sa.Column('delivered_at', sa.DateTime(), nullable=True, comment='When notification was delivered (if tracked)'),
    sa.Column('failed_at', sa.DateTime(), nullable=True, comment='When notification failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='Service provider used (twilio, termii, etc.)'),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True, comment="Provider's message ID for tracking"),
    sa.Column('triggered_by', sa.String(length=50), nullable=False, comment='What triggered this notification (scheduler, manual, etc.)'),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True, comment='User who triggered (if manual)'),
    sa.Column('batch_id', sa.UUID(), nullable=True, comment='Batch ID for grouped notifications'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When log entry was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_batch', 'notification_logs', ['batch_id', 'status'], unique=False)
    op.create_index('idx_notification_recipient_date', 'notification_logs', ['recipient_id', 'sent_at'], unique=False)
    op.create_index('idx_notification_status_channel', 'notification_logs', ['status', 'channel', 'created_at'], unique=False)
    op.create_index('idx_notification_type_date', 'notification_logs', ['notification_type', 'sent_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_batch_id'), 'notification_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_notification_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_recipient_id'), 'notification_logs', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_sent_at'), 'notification_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('patient_type', sa.Enum('REGULAR', 'PREGNANT', name='patienttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'POSTPARTUM', 'COMPLETED', 'INACTIVE', name='patientstatus'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('accepts_messaging', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_accepts_messaging'), 'patients', ['accepts_messaging'], unique=False)
    op.create_index(op.f('ix_patients_created_by_id'), 'patients', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_patients_facility_id'), 'patients', ['facility_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=True)
    op.create_index(op.f('ix_patients_is_deleted'), 'patients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_patient_type'), 'patients', ['patient_type'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(op.f('ix_patients_updated_by_id'), 'patients', ['updated_by_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('absolute_expiry', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False, comment='Fixed ID=1 for singleton pattern'),
    sa.Column('notification_target', sa.String(length=50), nullable=False, comment='Target audience for notifications'),
    sa.Column('reminder_interval_days', sa.Integer(), nullable=False, comment='Days between vaccination reminders (1-30)'),
    sa.Column('reminder_message', sa.Text(), nullable=True, comment='Custom reminder message template'),
    sa.Column('dashboard_refresh_rate_seconds', sa.Integer(), nullable=False, comment='Auto-refresh interval in seconds (10-300)'),
    sa.Column('enable_dashboard_auto_refresh', sa.Boolean(), nullable=False, comment='Enable/disable dashboard auto-refresh'),
    sa.Column('system_status', sa.String(length=20), nullable=False, comment='Current system operational status'),
    sa.Column('maintenance_message', sa.Text(), nullable=True, comment='Message displayed during maintenance'),
    sa.Column('maintenance_start', sa.DateTime(), nullable=True, comment='Scheduled maintenance start time'),
    sa.Column('maintenance_end', sa.DateTime(), nullable=True, comment='Scheduled maintenance end time'),
    sa.Column('require_device_approval', sa.Boolean(), nullable=False, comment='Require admin approval for new devices'),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, comment='User session timeout in minutes (30-1440)'),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False, comment='Maximum failed login attempts before lockout (3-10)'),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False, comment='Account lockout duration in minutes (10-120)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Settings creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='User who last updated settings'),
    sa.CheckConstraint('dashboard_refresh_rate_seconds >= 10 AND dashboard_refresh_rate_seconds <= 300', name='valid_refresh_rate'),
    sa.CheckConstraint('id = 1', name='single_settings_row'),
    sa.CheckConstraint('lockout_duration_minutes >= 10 AND lockout_duration_minutes <= 120', name='valid_lockout_duration'),
    sa.CheckConstraint('max_login_attempts >= 3 AND max_login_attempts <= 10', name='valid_max_login_attempts'),
    sa.CheckConstraint('reminder_interval_days >= 1 AND reminder_interval_days <= 30', name='valid_reminder_interval'),
    sa.CheckConstraint('session_timeout_minutes >= 30 AND session_timeout_minutes <= 1440', name='valid_session_timeout'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settings_status', 'settings', ['system_status'], unique=False)
    op.create_index('idx_settings_updated', 'settings', ['updated_at'], unique=False)
    op.create_index(op.f('ix_settings_notification_target'), 'settings', ['notification_target'], unique=False)
    op.create_index(op.f('ix_settings_system_status'), 'settings', ['system_status'], unique=False)
    op.create_index(op.f('ix_settings_updated_at'), 'settings', ['updated_at'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('last_ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRUSTED', 'BLOCKED', 'SUSPICIOUS', name='devicestatus'), nullable=False),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_device_fingerprint'), 'trusted_devices', ['device_fingerprint'], unique=True)
    op.create_index(op.f('ix_trusted_devices_id'), 'trusted_devices', ['id'], unique=True)
    op.create_index(op.f('ix_trusted_devices_status'), 'trusted_devices', ['status'], unique=False)
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('session_token', sa.String(length=512), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('login_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('is_terminated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vaccines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('price_per_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_batch_number'), 'vaccines', ['batch_number'], unique=False)
    op.create_index(op.f('ix_vaccines_id'), 'vaccines', ['id'], unique=True)
    op.create_index(op.f('ix_vaccines_is_published'), 'vaccines', ['is_published'], unique=False)
    op.create_index(op.f('ix_vaccines_vaccine_name'), 'vaccines', ['vaccine_name'], unique=False)
    op.create_table('diagnosis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('preliminary_diagnosis', sa.Text(), nullable=True),
    sa.Column('actual_diagnosis', sa.Text(), nullable=True),
    sa.Column('diagnose_by_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('diagnosed_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagnose_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_id'), 'diagnosis', ['id'], unique=True)
    op.create_index(op.f('ix_diagnosis_is_deleted'), 'diagnosis', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_diagnosis_patient_id'), 'diagnosis', ['patient_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('months_supply', sa.Integer(), nullable=True),
    sa.Column('next_dose_due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('lab_review_scheduled', sa.Boolean(), nullable=False),
    sa.Column('lab_review_date', sa.Date(), nullable=True),
    sa.Column('lab_review_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_id'), 'medication_schedules', ['id'], unique=True)
    op.create_index(op.f('ix_medication_schedules_next_dose_due_date'), 'medication_schedules', ['next_dose_due_date'], unique=False)
    op.create_index(op.f('ix_medication_schedules_patient_id'), 'medication_schedules', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_scheduled_date'), 'medication_schedules', ['scheduled_date'], unique=False)
    op.create_table('patient_vaccine_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('price_per_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('total_doses', sa.Integer(), nullable=False),
    sa.Column('total_package_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('doses_administered', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_vaccine_purchases_batch_number'), 'patient_vaccine_purchases', ['batch_number'], unique=False)
    op.create_index(op.f('ix_patient_vaccine_purchases_id'), 'patient_vaccine_purchases', ['id'], unique=True)
    op.create_index(op.f('ix_patient_vaccine_purchases_is_active'), 'patient_vaccine_purchases', ['is_active'], unique=False)
    op.create_index(op.f('ix_patient_vaccine_purchases_patient_id'), 'patient_vaccine_purchases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_vaccine_purchases_payment_status'), 'patient_vaccine_purchases', ['payment_status'], unique=False)
    op.create_index(op.f('ix_patient_vaccine_purchases_vaccine_id'), 'patient_vaccine_purchases', ['vaccine_id'], unique=False)
    op.create_table('pregnant_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('gestational_age_weeks', sa.Integer(), nullable=True),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnant_patients_expected_delivery_date'), 'pregnant_patients', ['expected_delivery_date'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('prescription_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=True)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_date'), 'prescriptions', ['prescription_date'], unique=False)
    op.create_table('regular_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('viral_load', sa.String(length=100), nullable=True),
    sa.Column('last_viral_load_date', sa.Date(), nullable=True),
    sa.Column('treatment_start_date', sa.Date(), nullable=True),
    sa.Column('treatment_regimen', sa.String(length=255), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mother_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=True),
    sa.Column('six_month_checkup_date', sa.Date(), nullable=True),
    sa.Column('six_month_checkup_completed', sa.Boolean(), nullable=False),
    sa.Column('hep_b_antibody_test_result', sa.String(length=100), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['pregnant_patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_date_of_birth'), 'children', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=True)
    op.create_index(op.f('ix_children_mother_id'), 'children', ['mother_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaccine_purchase_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vaccine_purchase_id'], ['patient_vaccine_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_vaccine_purchase_id'), 'payments', ['vaccine_purchase_id'], unique=False)
    op.create_table('vaccinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_purchase_id', sa.UUID(), nullable=False),
    sa.Column('dose_number', sa.Enum('FIRST_DOSE', 'SECOND_DOSE', 'THIRD_DOSE', name='dosetype'), nullable=False),
    sa.Column('dose_date', sa.Date(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('vaccine_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('administered_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_purchase_id'], ['patient_vaccine_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_dose_date'), 'vaccinations', ['dose_date'], unique=False)
    op.create_index(op.f('ix_vaccinations_dose_number'), 'vaccinations', ['dose_number'], unique=False)
    op.create_index(op.f('ix_vaccinations_id'), 'vaccinations', ['id'], unique=True)
    op.create_index(op.f('ix_vaccinations_patient_id'), 'vaccinations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vaccinations_vaccine_purchase_id'), 'vaccinations', ['vaccine_purchase_id'], unique=False)
    op.create_table('patient_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.Enum('DELIVERY_WEEK', 'CHILD_6MONTH_CHECKUP', 'MEDICATION_DUE', 'PAYMENT_DUE', 'VACCINATION_DUE', name='remindertype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_reminders_id'), 'patient_reminders', ['id'], unique=True)
    op.create_index(op.f('ix_patient_reminders_patient_id'), 'patient_reminders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_reminders_reminder_type'), 'patient_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_patient_reminders_scheduled_date'), 'patient_reminders', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_patient_reminders_status'), 'patient_reminders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_reminders_status'), table_name='patient_reminders')
    op.drop_index(op.f('ix_patient_reminders_scheduled_date'), table_name='patient_reminders')
    op.drop_index(op.f('ix_patient_reminders_reminder_type'), table_name='patient_reminders')
    op.drop_index(op.f('ix_patient_reminders_patient_id'), table_name='patient_reminders')
    op.drop_index(op.f('ix_patient_reminders_id'), table_name='patient_reminders')
    op.drop_table('patient_reminders')
    op.drop_index(op.f('ix_vaccinations_vaccine_purchase_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_patient_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_id'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_dose_number'), table_name='vaccinations')
    op.drop_index(op.f('ix_vaccinations_dose_date'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_index(op.f('ix_payments_vaccine_purchase_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_children_mother_id'), table_name='children')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index(op.f('ix_children_date_of_birth'), table_name='children')
    op.drop_table('children')
    op.drop_table('regular_patients')
    op.drop_index(op.f('ix_prescriptions_prescription_date'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_pregnant_patients_expected_delivery_date'), table_name='pregnant_patients')
    op.drop_table('pregnant_patients')
    op.drop_index(op.f('ix_patient_vaccine_purchases_vaccine_id'), table_name='patient_vaccine_purchases')
    op.drop_index(op.f('ix_patient_vaccine_purchases_payment_status'), table_name='patient_vaccine_purchases')
    op.drop_index(op.f('ix_patient_vaccine_purchases_patient_id'), table_name='patient_vaccine_purchases')
    op.drop_index(op.f('ix_patient_vaccine_purchases_is_active'), table_name='patient_vaccine_purchases')
    op.drop_index(op.f('ix_patient_vaccine_purchases_id'), table_name='patient_vaccine_purchases')
    op.drop_index(op.f('ix_patient_vaccine_purchases_batch_number'), table_name='patient_vaccine_purchases')
    op.drop_table('patient_vaccine_purchases')
    op.drop_index(op.f('ix_medication_schedules_scheduled_date'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_patient_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_next_dose_due_date'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_diagnosis_patient_id'), table_name='diagnosis')
    op.drop_index(op.f('ix_diagnosis_is_deleted'), table_name='diagnosis')
    op.drop_index(op.f('ix_diagnosis_id'), table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index(op.f('ix_vaccines_vaccine_name'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_is_published'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_id'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_batch_number'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_trusted_devices_user_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_status'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_device_fingerprint'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_settings_updated_at'), table_name='settings')
    op.drop_index(op.f('ix_settings_system_status'), table_name='settings')
    op.drop_index(op.f('ix_settings_notification_target'), table_name='settings')
    op.drop_index('idx_settings_updated', table_name='settings')
    op.drop_index('idx_settings_status', table_name='settings')
    op.drop_table('settings')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patients_updated_by_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_type'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_deleted'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_facility_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_by_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_accepts_messaging'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_sent_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_recipient_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_notification_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_batch_id'), table_name='notification_logs')
    op.drop_index('idx_notification_type_date', table_name='notification_logs')
    op.drop_index('idx_notification_status_channel', table_name='notification_logs')
    op.drop_index('idx_notification_recipient_date', table_name='notification_logs')
    op.drop_index('idx_notification_batch', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_device_fingerprint'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_geographic_restrictions_facility_id'), table_name='geographic_restrictions')
    op.drop_table('geographic_restrictions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_manager_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_email'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_created_at'), table_name='facilities')
    op.drop_index('idx_facility_manager_created', table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
